<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="CascadiaMono.ttf" />
    <EmbeddedResource Include="tool.png" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="NativeFileDialogNET" Version="2.0.2" />
	<PackageReference Include="BCnEncoder.Net" Version="2.2.1" />
    <PackageReference Include="Silk.NET.Assimp" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />

    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12"/>
  </ItemGroup>

</Project>
