<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Phoenix.AssetTool</PackageId>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>pat</ToolCommandName>
    <TargetFramework>net10.0</TargetFramework>
    <PackageOutputPath>C:\dev\LocalNuget</PackageOutputPath>
    <Authors>leanosuna</Authors>
    <Product>Phoenix.AssetTool</Product>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>1.0.1-alpha-1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.5" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Phoenix.AssetTool.Core\Phoenix.AssetTool.Core.csproj" />
    <ProjectReference Include="..\Phoenix.AssetTool.Gui\Phoenix.AssetTool.Gui.csproj" />
  </ItemGroup>

</Project>
